### PR TITLE
Add initial support for reddit.com/r/random

### PR DESCRIPTION
**Pull request by djjcast**
Here's some initial support for reddit.com/r/random for evaluation.

A new subreddit is loaded when the content is refreshed by "pulling down" or using the "refresh" menu button. A new subreddit is also loaded when the sorting type is changed (like from "hot" to "rising") - I'm not sure if this behavior is appropriate.

I wasn't sure how best to integrate the changes so feel free to modify and cleanup the code.

See also https://github.com/ccrama/reddift/pull/3.

### CODE REVIEW

**Comment by ccrama** [comment]
Great work, thank you for the PR! In the reddift PR, I am trying to understand the code, but it seems as if you are doing a request to get the subreddit and then another request using the closures of the new subreddit, can you confirm that is how it works? 

Otherwise, thank you very much for the PR!

**Comment by ccrama** [comment]
Also I really like the addition of a gold check in the AccountController!

**Comment by ccrama** [comment]
One request I have, though, is to remove random from the list of default subs

**Comment by djjcast** [comment]
Yes, /r/random and the other random urls work through redirection which the initial request is handling.

Okay, I wasn't sure when to show the random urls in the subreddit list. The random urls are like /r/all and /r/frontpage in that they can't be subscribed to - how can a user add /r/random to their subreddit list if it's not their by default (it's currently possible to remove it but not add it)?

A similar issue: how can a user add /r/all and /r/frontpage back to their subreddit list if they remove them through the "Manage your subreddits" menu?

**Comment by ccrama** [comment]
Oh interesting, I didn't realize that there was no way to add a subreddit from the manage subs screen. I will add that into the app asap! Would you be able to make those changes before I merge it (and I'll add that ability from the new subreddit add button)?

**Comment by djjcast** [comment]
Okay, I pushed the changes.

**Comment by ccrama** [comment]
Perfect, thank you very much! I have added the new button in the Reorder VC as well :)

**Comment by djjcast** [comment]
Okay, thanks. I just tried it and it seems like Podfile.lock is installing and older version reddift without the recent changes. Also, the name of the collection is "randnsfw" not "randomnsfw" here: https://github.com/ccrama/Slide-iOS/commit/8a08ef75fe7b095ca15cfb2f0ce8cfb0b7c58129#diff-fa6c6149e6752d67b2d10ffce23b148bR38

**Comment by ccrama** [comment]
Oops good find! Have fixed the NSFW sub. As for the pod, I have updated the podlock and will push that soon 👍

**Pull request merged**
