### PR TITLE
Initial pan title to upvote/downvote/save/hide implementation

### PR DESCRIPTION
**Pull request by djjcast**
See https://github.com/ccrama/Slide-iOS/issues/465.

### CODE REVIEW

**Comment by ccrama** [comment]
Really great idea, thank you for the implementation!

Some things that need to be done (will be taking a look at soon):

- [ ] Switch to using the enum for post actions (also hook into the execution method for those gestures so it's all dynamic)
- [ ] Add left and right swipe to the Settings > Gestures screen
- [ ] Flash animation or reversal of the animation to show that it was "complete"
- [ ] Use the post action enum photo for the icon in the center of the card while the animation is running

**Comment by ccrama** [comment]
Let me know what you think of my changes @djjcast @colejd :)

**Comment by djjcast** [comment]
I am not able to set submission swipe gestures with my 6 Plus on 10.3.3. This is what I see when scrolled to the bottom of the "Gestures" settings page: https://i.imgur.com/iWhUDCf.png

The issue seems to be that these options are stored using `UISwipeActionsConfiguration` which is not supported before iOS 11.0: https://github.com/ccrama/Slide-iOS/blob/master/Slide%20for%20Reddit/SettingsGestures.swift#L272

**Comment by djjcast** [comment]
Sorry, false alarm, I download my fork (which wasn't up to date) instead of the main repo to test the changes. The above issue is not present on the latest version - I'll test some more and report back.

**Comment by djjcast** [comment]
After testing the changes for a while, I can say I personally like them. I like how you made it possible to swipe on the banner image/video to perform an action.

Although, I can imagine if the current version was released to the masses as is, there would be reports of submission swiping not working since it's not immediately obvious to the user that you can only swipe on the title and banner image/video to perform an action. I even caught myself trying to swipe on the gray area between the title and action bar or thumbnail  - even though I know where the swipe areas are: https://i.imgur.com/pwHNYKA.png

I was wondering, to enable "swipe from anywhere within the cell area", would it be possible to overlay a transparent UIView over the cell whose sole purpose is to handle the sliding pan gesture? Other UI events would have to pass through this transparent overlay view (like tap and double tap). Also, I'm not sure what other technical limitations there might be.

**Comment by ccrama** [comment]
So the issue with making the whole cell swiping is it would disable swiping left and right between subreddits and inside the comments view. That would be a pretty big tradeoff IMO and I feel there is a way to have both active and available. What if there was some sort of view in the cell that was made exclusively for swiping? If you have any other ideas I'm all for it! @djjcast @colejd

**Comment by djjcast** [comment]
The idea of having a dedicated swiping view/area sounds interesting.

I personally don't use the swiping subreddit tabs mode since I prefer to use the bottom drawer. What if there was a setting like the one for the comment/post view where you can choose if you want to swipe to the next post with one or two fingers? Then the whole cell area can be swipable and for the tabs mode you could choose between:

a. one finger swipe to go to the next tab and two finger swipe to perform a post action
b. one finger swipe to perform a post action and two finger swipe to go to the next tab

**Comment by djjcast** [comment]
Another idea is to have the whole cell area swipable by default and have a setting so the user can set left and right insets (customizable size) where submission swiping isn't recognized.

**Pull request merged**
