### PR TITLE
Features/colejd/important/uicolor black magic

### PR DESCRIPTION
**Pull request by colejd**
¯\\_(ツ)_/¯

### CODE REVIEW

**Comment by ccrama** [comment]
Also could we get an undo function :D

**Comment by colejd** [comment]
We can undo, yeah. I'll work on it haha.

Also... maybe? The reviewers have a static analysis tool that searches by string for references to private headers, so we won't set anything off there, but I think we're fine. You can't link against private frameworks but we're not. If we want to be extra safe we can go with the less invasive method that swizzles a `UIColor.red` instance, which I'm sure is safe (if misguided).

**Comment by ccrama** [comment]
Thank you this is so cool, keep coming with the memes

**Comment by ccrama** [comment]
I merged this through the command line

**Pull request closed without merging**
