### PR TITLE
* fix crash bug when url contains special character

### PR DESCRIPTION
**Pull request by certainly**
Fix crash bug when url contains special character in user overview or comment history 

This bug also happens in many code places where "URL.init(string: url)" is used. Maybe a wrapper or extension on URL.init() should be a solution.

[test url](https://reddit.com/r/saraba1st/comments/athotk/%E6%8E%A8%E7%89%B9%E4%B8%8A%E6%90%9C%E7%8E%8B%E6%9E%97%E6%B8%85/)

### CODE REVIEW

**Comment by ccrama** [comment]
Thank you for the PR @certainly!

Do you have steps for reproduction for this issue as of the latest master commit? If I visit that user's profile as of 3ec66c3ccc8b0d3a5edb03bdc7fc0a0e31c3aa57 and click on that comment link, I do not crash.

There are definitely some issues creating URLs with special characters, and an extension might be the way to go in order to fix that issue across all of the app 👍

**Comment by certainly** [comment]
Thank u for making this terrific app!  I used Apollo before, now I'm using Slide to make my own change for lookup word definition. I believe Slide will definitely gain a grand future.
 
This bug occurs in the login user's comments history. It crash only in urls with special characters, for example the test url I posted above which contains Chinese characters.

So for reproduction you may need to make comment in the test url, then click it from your comment karma.

call stack:
CommentCellView.openComment(sender:)  --->  VCPresenter.openRedditLink(_:_:_:)

**Comment by ccrama** [comment]
I am going to look into making this an extension for URL that we can implement throughout the app :)

If you would like to take a stab at it be my guest!

**Comment by certainly** [comment]
Just read the comment. 
I think to override URL.init() would be the best solution but couldn't do that. 
So had to add a new initializer in extension –––– URL.initPercent(string: String), see commit 95cb116
Wish there's a better solution

**Comment by ccrama** [comment]
That looks like a good compromise, will use that in the future :)

Thanks for the PR!

**Pull request merged**
